version: '3.1'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: celery
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: celery_sender

    ports:
      - 5430:5432
